EXPLOTION_IMAGE = "explotion.png"
FLAG_IMAGE = "flag.png"
GRASS_IMAGE = "grass.png"
INJURY_IMAGE = "injury.png"
MINE_IMAGE = "mine.png"
SNAKE_IMAGE = "snake.png"
SOLDIER_IMAGE = "soldier.png"
SOLDIER_2_IMAGE = "soldier (2).png"
SOLDIER_NIGTH_IMAGE =  "soldier_nigth.png"

IMAGE_SOLDIER_HEIGHT = 4
IMAGE_SOLDIER_WIDTH = 2
BODY_SOLDIER = 6
LEGS_SOLDIER = 2
IMAGE_FLAG_HEIGHT = 3
IMAGE_FLAG_WIDTH = 4
IMAGE_MINE_HEIGHT = 1
IMAGE_MINE_WIDTH = 3

WINDOW_TITLE = "The Flag"
SCREEN_SIZE = (1250, 625)
WHITE = (255, 255, 255)
BACKGROUND_COLOR = (9, 99, 0)
FONT = "ariel"
WELCOME = "Welcome to The Flag game."
HAVE_FUN = "Have Fun!"
WIN_MESSAGE = "You Won"
LOSE_MESSAGE = "You Lost"
MASSAGE_END_TIME = 3
VISIBLE_TIME = 1
AMOUNT_GRASS_IMAGES = 20
GAME_ROWS = 25
GAME_COLS = 50



